commerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    # Entry page url
    path("wiki/info/<str:entry>", views.entry_page, name="entry_page"),
    # Search entry url
    path("wiki/search", views.search_entry, name="search_entry"),
    # Add a new page
    path("wiki/add-page", views.add_page, name="add_page"),
    # Edit the content of an entry
    path("wiki/edit/<str:entry>", views.edit_entry, name="edit_page"),
    # Random entry url 
    path("wiki/random", views.random_entry, name="random_page")

]

project3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mail.urls'))
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/views.py
from cProfile import label
from logging import PlaceHolder
import random
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django import forms
from django.contrib import messages

from . import util
import markdown2

############
#  FORMS   #
############

class SearchEntryForm(forms.Form):
    entry = forms.CharField(label="", widget=forms.TextInput(
        attrs={
            'placeholder': 'Search Encyclopedia',
            'class' : 'search'
        }
    ))


class NewEntryForm(forms.Form): 
    title = forms.CharField(label="Title", min_length=1, widget=forms.TextInput(
        attrs={
            'placeholder': 'Title', 
            'class' : 'search w-50 m-2'
        }
    ))

    content = forms.CharField(min_length=1, widget=forms.Textarea(
        attrs={
            'placeholder': 'Markdown content',
            'class' : 'search w-50 m-2'
        }
    ))


###############
#    Views    #
###############

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form" : SearchEntryForm()
    })


def entry_page(request, entry):
    '''
        Show the requested entry information in a page
    '''
    # Get the Entry Markdown content
    entry_content = util.get_entry(entry)

    if not entry_content:
        # The requested entry does not exist and show an error page
        return render(request, "encyclopedia/error_page.html", {
            "entry" : entry,
            "message" : f"The page {entry} was not found!",
            "form" : SearchEntryForm()
        })
    
    # Convert from Markdown to HTML
    entry_content = markdown2.markdown(entry_content)
    return render(request, "encyclopedia/entry_page.html", {
        "entry" : entry,
        "entry_content" : entry_content,
        "form" : SearchEntryForm()
    })


def search_entry(request):
    if request.method == "POST":
        form = SearchEntryForm(request.POST)
        if form.is_valid():
            # Get the entry value
            entry = form.cleaned_data["entry"]
            # Get the Entry markdown content
            entry_content = util.get_entry(entry.lower())
            if entry_content:
                # Redirect to the requested entry page if the content does exist
                return HttpResponseRedirect(reverse("encyclopedia:entry_page", kwargs={"entry" : entry}))
            if entry and not entry_content:
                # The user requested a non-empty entry, but it does not exist
                similar_entries = util.get_similar_entries(entry)
                return render(request, "encyclopedia/search_results.html", {
                    "similar_entries" : similar_entries,
                    "form" : SearchEntryForm(),
                    "entry" : entry
                })
    # Return to the index page if the entry is empty
    return HttpResponseRedirect(reverse("encyclopedia:index"))


def add_page(request):
    if request.method == "POST":
        entry_form = NewEntryForm(request.POST)
        if entry_form.is_valid():
            # Get the data from the form
            title = entry_form.cleaned_data['title']
            content = entry_form.cleaned_data.get('content')
            # Save the data from the form
            util.save_entry(title, content)
            # Notify that the data was saved sucessfully
            messages.success(request, f"{ title } was added succcessfully!" )
            return HttpResponseRedirect(reverse("encyclopedia:index"))
        else: 
            # Notify that there was an error
            messages.error(request, "The form is not valid!")
            return render(request, "encyclopedia/add_page.html", {
                "form_add" : entry_form,
                "form" : SearchEntryForm()
            })
    
    return render(request, "encyclopedia/add_page.html", {
        "form_add" : NewEntryForm(),
        "form" : SearchEntryForm()
    })


def edit_entry(request, entry):
    if request.method == "POST":
        edit_form = NewEntryForm(request.POST)
        
        if edit_form.is_valid():
            # Get the edited data from the form
            content = edit_form.cleaned_data.get('content')
            # Save the edited data from the form
            util.save_entry(entry, content)
            # Notify that the data was edited sucessfully
            messages.success(request, f"{ entry } was edited succcessfully!" )
            return HttpResponseRedirect(reverse("encyclopedia:index"))
        else: 
            # Notify that there was an error
            messages.error(request, "The form is not valid!")
            return render(request, "encyclopedia/edit_page.html", {
                "edit_form" : edit_form,
                "form" : SearchEntryForm(), 
                'entry' : entry
            })

    # Get the saved Markdown content of the entry
    entry_content = util.get_entry(entry)
    # Initialize the form with the information of the entry
    edit_form = NewEntryForm(initial={'title': entry, 'content' : entry_content })
    # Set the title field as readonly
    edit_form.fields['title'].widget.attrs['readonly'] = True 

    return render(request, "encyclopedia/edit_page.html", {
        'form' : SearchEntryForm(),
        'edit_form' : edit_form,
        'entry' : entry
    })


def random_entry(request):
    entry = random.choice(util.list_entries())
    return HttpResponseRedirect(reverse('encyclopedia:entry_page', args=[entry,]))

encyclopedia/templates/encyclopedia/add_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Add page
{% endblock %}

{% block body %}
    <form action="{% url 'encyclopedia:add_page' %}" method="post" class="d-flex flex-column h-75 align-items-center justify-content-center mt-5">
        {% csrf_token %}
        {{ form_add }}
        <input type="submit" value="Add page" class="btn btn-primary w-25 mt-3">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Add page
{% endblock %}

{% block body %}
    <form action="{% url 'encyclopedia:edit_page' entry %}" method="post" class="d-flex flex-column h-75 align-items-center justify-content-center mt-5">
        {% csrf_token %}
        {{ edit_form }}
        <input type="submit" value="Edit content" class="btn btn-primary w-25 mt-3">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ entry }}
{% endblock %}

{% block body %}
    <!-- Entry markdown content in HTML -->
    <a href="{% url 'encyclopedia:edit_page' entry %}">Edit content</a>
    {{ entry_content | safe}}
{% endblock %}

encyclopedia/templates/encyclopedia/error_page.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
    Error
{% endblock %}
{% block body %}
    <h1 class="error">Error!</h1>
    {{ message }}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry_page' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <script src="{% static 'encyclopedia/alerts.js' %}"></script>
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    </head>
    <body>
        {% if messages %}
            {% for message in messages %}
                <script>show_message("{{message.tags}}", "{{message}}", "{{message.tags}}");</script>
            {% endfor %}
        {% endif %}
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="post" action="{% url 'encyclopedia:search_entry' %}">
                    {% csrf_token %}
                    {{ form }}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
    Search Results
{% endblock %}
{% block body %}
    <h1>Results similar to "{{ entry }}"</h1>
    
    <ul>
        {% for similar_entry in similar_entries %}
            <li><a href="{% url 'encyclopedia:entry_page' similar_entry %}">{{ similar_entry }}</a></li>
        {% empty %}
            <p>There are no entries similar to "{{entry}}"</p>
        {% endfor %}
    </ul>
{% endblock %}